### ISSUE TITLE
'float' object has no attribute 'get'

### ISSUE THREAD

**Issue by octacian** [eric-with-a-c/resolve-otio#1]
Hi there, I've been trying to automate some timeline work and ended up being forced to turn to OpenTimelineIO. I've tried running the script under Python 2.7 as well as Python 3.6 but no matter what I keep getting this error:

```
'float' object has no attribute 'get'
```

I dug into the python a bit but nothing was too obvious and I'm running on a tight schedule right now so I figured I would just report it here. In the meantime I'll probably export the timeline to an FCPXML as a go-between.

If it helps at all, I'm running on Arch Linux with Python paths symbolically linked to semi-replicate the CentOS file structure.

**Comment by eric-with-a-c** [comment]
Hi @octacian! 

Which version of Resolve are you using?

**Comment by octacian** [comment]
Oh sorry! I completely forgot to include that in the issue.

When I first came across this issue I was using DaVinci Resolve 17.4.1 Build 4. I just updated to 17.4.2 Build 9 and am having the exact same issue.

**Comment by eric-with-a-c** [comment]
@octacian This is finally fixed now with the most recent changes. Sorry for taking so long to get to it.
